export type ContentType = 'movie' | 'series' | 'sport' | 'live' | 'documentary';

export interface Moment {
  id: string;
  title: string;
  timestamp: string;
  thumbnailUrl: string;
}

export interface ContentItem {
  id: string;
  title: string;
  description: string;
  type: ContentType;
  genre: string[];
  tags: string[];
  thumbnailUrl: string;
  heroUrl: string;
  duration?: string;
  year?: string;
  rating?: string;
  cast?: string[];
  moments?: Moment[];
  trending?: boolean;
  personalizedScore?: number;
}

const tmdb = (path: string) => `https://image.tmdb.org/t/p/w500/${path}`;

const PACKSHOTS = {
  nba_finals: tmdb("bv47XMjZUhptKGFKIEoVA8pVsMT.jpg"),
  silent_peaks: tmdb("At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg"),
  wimbledon: tmdb("5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg"),
  midnight_drive: tmdb("k50021gkK92Lx6m99pBy6FUOvNf.jpg"),
  signal_lost: tmdb("lCySuYjhXix3FzQdS4oceDDrXKI.jpg"),
  arsenal_liverpool: tmdb("sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg"),
  last_heist: tmdb("u38k3hQBDwNX0VA22aQceDp9Iyv.jpg"),
  breaking_point: tmdb("u525jeDOzg9hVdvYfeehTGnw7Aa.jpg"),
  tour_france: tmdb("mflBcox36s9ZPbsZPVOuhf6axaJ.jpg"),
  ember: tmdb("mQ7076pL4Ac0ZzY4w31labWIdQt.jpg"),
  olympics_sprint: tmdb("jxAbDJWvz4p1hoFpJYG5vY2dQmq.jpg"),
  kitchen_wars: tmdb("jqrYg35GHuMGwGqEVUthqTLQnay.jpg"),
  velocity: tmdb("6RVxNlNmc0DIfZzaJKCJM43If3M.jpg"),
  rugby_wc: tmdb("ie1KbeYFG5E0GVr1QP7tDNuXvga.jpg"),
  echoes: tmdb("dlffgYbqr1BllWacVLhAFw23nLl.jpg"),
  frost: tmdb("5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg"),
  aus_open: tmdb("trzgptffGvAlAT6MEu01fz47cLW.jpg"),
  informant: tmdb("zQp2YM0zbC27Ws97LNbyicysk8p.jpg"),
  laugh_track: tmdb("yRTElSeC3q9nBqBuleI6OODlDMS.jpg"),
  ufc: tmdb("coC58ANiDbqRIyle5zEl9QDektf.jpg"),
  glass_tower: tmdb("8RZLOyYGsoRe9p44q3xin9QkMHv.jpg"),
  homestead: tmdb("y40Wu1T742kynOqtwXASc5Qgm49.jpg"),
  cricket_wc: tmdb("vQSqH3ybDWZHZIqX4NZKhOCXAhQ.jpg"),
  whisper: tmdb("ut7ewXjdgUmgkhJ1EtbOo9tbc7s.jpg"),
  dark_frequency: tmdb("1mm7JGHIUX3GRRGXEV9QCzsI0ao.jpg"),
  six_nations: tmdb("9CAd7wr8QZyIN0E7nm8v1B6WkGn.jpg"),
  starbound: tmdb("axENiFIrSz5B7UuWkMT7PDe7CaO.jpg"),
  standup_raw: tmdb("8LqG2N6j98lFGMpuYsRUAhOunSd.jpg"),
  la_liga: tmdb("fOMFO2Xx4duzpNgS9Q5ytO44yGb.jpg"),
  last_light: tmdb("2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg"),
  efl_cup: tmdb("5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg"),
  womens_euro: tmdb("k9KGzGDVhXKfOGpoN62MNuXL28q.jpg"),
  intl_football: tmdb("npIIZJGSrcJIJ6yHdmbqO6Jzo5I.jpg"),
  match_analysis: tmdb("xr2GSp8Pm6fT5VGm0I9tsWVcZ8q.jpg"),
  investigation: tmdb("i6fHvGt7Rb8oVyjjdQVV6vEHB94.jpg"),
  coastline: tmdb("5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg"),
  last_stand: tmdb("ie1KbeYFG5E0GVr1QP7tDNuXvga.jpg"),
  royal_household: tmdb("9CAd7wr8QZyIN0E7nm8v1B6WkGn.jpg"),
  moment_1: tmdb("u525jeDOzg9hVdvYfeehTGnw7Aa.jpg"),
  moment_2: tmdb("dlffgYbqr1BllWacVLhAFw23nLl.jpg"),
  moment_3: tmdb("sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg"),
  moment_4: tmdb("bv47XMjZUhptKGFKIEoVA8pVsMT.jpg"),
  moment_5: tmdb("At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg"),
  moment_6: tmdb("trzgptffGvAlAT6MEu01fz47cLW.jpg"),
  moment_7: tmdb("jxAbDJWvz4p1hoFpJYG5vY2dQmq.jpg"),
  moment_8: tmdb("vQSqH3ybDWZHZIqX4NZKhOCXAhQ.jpg"),
};

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: "hero_marty",
    title: "Marty Supreme",
    description: "Set in 1950s New York, a shoe salesman and table tennis hustler pursues his obsessive dream of becoming world champion. Based on the extraordinary life of legendary ping-pong player Marty Reisman.",
    type: "movie",
    genre: ["Drama", "Sport", "Biography"],
    tags: ["marty supreme", "timothee chalamet", "ping pong", "table tennis", "a24", "josh safdie", "drama", "sport", "biography", "1950s", "new york"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/qKWDHofjMHPSEOTLaixkC9ZmjTT.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3iMoYSbI72Nwsvi7uSpqReLJVa6.jpg",
    duration: "2h 17m",
    year: "2025",
    rating: "15",
    cast: ["Timothée Chalamet", "Gwyneth Paltrow", "Tyler, the Creator"],
    trending: true,
    personalizedScore: 99
  },
  {
    id: "s1",
    title: "The White Lotus",
    description: "A satirical comedy-drama set at an exclusive tropical resort, following the vacations of various hotel guests over the span of a week as dark secrets unravel.",
    type: "series",
    genre: ["Drama", "Comedy"],
    tags: ["drama", "comedy", "series", "hbo", "resort", "satire", "thriller", "white lotus"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/7n06DhBEVVBDLxSwQK1RCUfeUbH.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/rCTLaPwuApDx8vLGjYZ9pRl7zRB.jpg",
    duration: "3 Seasons",
    year: "2021-2025",
    rating: "18+",
    cast: ["Jennifer Coolidge", "Aubrey Plaza", "Walton Goggins"],
    trending: true,
    personalizedScore: 98,
    moments: [
      { id: "m1a", title: "Incredible opening goal", timestamp: "12:05", thumbnailUrl: PACKSHOTS.moment_1 },
      { id: "m1b", title: "VAR Review — Penalty decision", timestamp: "44:30", thumbnailUrl: PACKSHOTS.moment_2 },
      { id: "m1c", title: "Last minute dramatic save", timestamp: "89:15", thumbnailUrl: PACKSHOTS.moment_3 },
      { id: "m1d", title: "Post-match celebrations", timestamp: "92:00", thumbnailUrl: PACKSHOTS.moment_4 }
    ]
  },
  {
    id: "m1",
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence. But when the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
    type: "movie",
    genre: ["Animation", "Action", "Adventure"],
    tags: ["animation", "action", "superhero", "marvel", "spider-man", "exciting", "multiverse", "adventure"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/uc5U4GCZu9Z2Zb3yqk5fZfLwawR.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    duration: "2h 20m",
    year: "2023",
    rating: "PG",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    trending: true,
    personalizedScore: 85
  },
  {
    id: "s2",
    title: "Peaky Blinders",
    description: "A gangster family epic set in 1920s Birmingham, England, centred on a gang who sew razor blades into the peaks of their caps. Tommy Shelby leads his fearless crew through the criminal underworld.",
    type: "series",
    genre: ["Crime", "Drama"],
    tags: ["crime", "drama", "series", "bbc", "gangster", "1920s", "thriller", "birmingham", "period"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/8qPdsHxxJU493XbjeYAXStRo7z.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    duration: "6 Seasons",
    year: "2013-2022",
    rating: "18+",
    cast: ["Cillian Murphy", "Helen McCrory", "Paul Anderson"],
    trending: true,
    personalizedScore: 92
  },
  {
    id: "d1",
    title: "Free Solo",
    description: "Academy Award-winning documentary following Alex Honnold's attempt to climb El Capitan without ropes — a breathtaking portrait of obsession and risk.",
    type: "documentary",
    genre: ["Adventure", "Sports"],
    tags: ["climbing", "adventure", "sports", "nature", "documentary", "inspiring", "extreme"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg",
    duration: "1h 40m",
    year: "2018",
    rating: "PG",
    personalizedScore: 88
  },
  {
    id: "se1",
    title: "The Garfield Movie",
    description: "Garfield, the world-famous Monday-hating, lasagne-loving indoor cat, is about to have a wild outdoor adventure. After an unexpected reunion with his long-lost father, Garfield and his canine friend Odie are forced into an epic heist.",
    type: "movie",
    genre: ["Animation", "Comedy", "Family"],
    tags: ["animation", "comedy", "family", "garfield", "kids", "cat", "adventure", "fun"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/4kgVYUQBM0USgffyn1gzEv3a4t4.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/P82NAcEsLIYgQtrtn36tYsj41m.jpg",
    duration: "1h 41m",
    year: "2024",
    rating: "PG",
    cast: ["Chris Pratt", "Samuel L. Jackson", "Hannah Waddingham"],
    trending: true,
    personalizedScore: 78
  },
  {
    id: "s3",
    title: "NBA Finals: Game 7",
    description: "It all comes down to this. The ultimate showdown for the championship ring in the most electrifying Game 7 in a decade.",
    type: "sport",
    genre: ["Basketball"],
    tags: ["nba", "basketball", "finals", "sports", "exciting", "intense", "game"],
    thumbnailUrl: PACKSHOTS.nba_finals,
    heroUrl: PACKSHOTS.nba_finals,
    duration: "2h 30m",
    year: "2024",
    personalizedScore: 88,
    moments: [
      { id: "m3a", title: "Buzzer beater three-pointer", timestamp: "119:45", thumbnailUrl: PACKSHOTS.moment_4 },
      { id: "m3b", title: "Incredible block at the rim", timestamp: "105:20", thumbnailUrl: PACKSHOTS.moment_5 }
    ]
  },
  {
    id: "m2",
    title: "Silent Peaks",
    description: "A solo climber attempts the impossible on the world's most dangerous mountain face. A story of human endurance against nature's fury.",
    type: "movie",
    genre: ["Adventure", "Drama"],
    tags: ["mountain", "climbing", "adventure", "snow", "intense", "survival"],
    thumbnailUrl: PACKSHOTS.silent_peaks,
    heroUrl: PACKSHOTS.silent_peaks,
    duration: "1h 55m",
    year: "2023",
    rating: "12+",
    cast: ["Anna Larsson"]
  },
  {
    id: "s4",
    title: "Wimbledon Men's Final",
    description: "Classic grass court action. An epic 5-set thriller that will go down in tennis history.",
    type: "sport",
    genre: ["Tennis"],
    tags: ["tennis", "wimbledon", "sports", "final", "grass", "exciting", "match"],
    thumbnailUrl: PACKSHOTS.wimbledon,
    heroUrl: PACKSHOTS.wimbledon,
    duration: "4h 10m",
    year: "2023",
    personalizedScore: 75
  },
  {
    id: "d2",
    title: "Planet Earth II",
    description: "BAFTA-winning sequel showcasing Earth's wildlife in dazzling detail, from urban jungles to remote islands. Narrated by David Attenborough.",
    type: "documentary",
    genre: ["Nature", "Wildlife"],
    tags: ["nature", "wildlife", "relaxing", "calm", "earth", "documentary", "animals", "attenborough"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/tUKomxy50suT4MyxjYfOJDkZUq3.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/1DYpBOVdb7Mzc9DgMCdIBTN1JEC.jpg",
    duration: "6 Episodes",
    year: "2016",
    rating: "U",
    personalizedScore: 92
  },
  {
    id: "m3",
    title: "Midnight Drive",
    description: "An underground getaway driver gets pulled into a heist that goes terribly wrong. Non-stop action from start to finish.",
    type: "movie",
    genre: ["Action", "Crime"],
    tags: ["cars", "driving", "action", "heist", "crime", "exciting", "thriller", "fast"],
    thumbnailUrl: PACKSHOTS.midnight_drive,
    heroUrl: PACKSHOTS.midnight_drive,
    duration: "1h 48m",
    year: "2022",
    rating: "15+",
    cast: ["Rico Alvarez", "Maya Knight"],
    trending: true,
    personalizedScore: 82
  },
  {
    id: "se2",
    title: "Signal Lost",
    description: "When a deep-space communication relay goes dark, a crew of engineers must travel to the edge of the solar system to find out why.",
    type: "series",
    genre: ["Sci-Fi", "Thriller"],
    tags: ["space", "sci-fi", "thriller", "exciting", "mystery", "series", "future"],
    thumbnailUrl: PACKSHOTS.signal_lost,
    heroUrl: PACKSHOTS.signal_lost,
    duration: "2 Seasons",
    year: "2023-2024",
    rating: "15+",
    cast: ["Kenji Tanaka", "Zara Ahmed"],
    personalizedScore: 90
  },
  {
    id: "s5",
    title: "Premier League: Arsenal vs Liverpool",
    description: "A top-of-the-table clash between two title contenders. The atmosphere at the Emirates was electric.",
    type: "sport",
    genre: ["Football", "Soccer"],
    tags: ["premier league", "arsenal", "liverpool", "football", "soccer", "sports", "match", "exciting"],
    thumbnailUrl: PACKSHOTS.arsenal_liverpool,
    heroUrl: PACKSHOTS.arsenal_liverpool,
    duration: "1h 55m",
    year: "2024",
    trending: true,
    personalizedScore: 95,
    moments: [
      { id: "m5a", title: "Goal from 30 yards", timestamp: "23:15", thumbnailUrl: PACKSHOTS.moment_6 },
      { id: "m5b", title: "Controversial red card", timestamp: "67:00", thumbnailUrl: PACKSHOTS.moment_7 }
    ]
  },
  {
    id: "m4",
    title: "The Last Heist",
    description: "A retired thief is forced back into action for one final job. But nothing is as it seems in this twisting crime saga.",
    type: "movie",
    genre: ["Crime", "Thriller"],
    tags: ["heist", "crime", "thriller", "action", "exciting", "twist"],
    thumbnailUrl: PACKSHOTS.last_heist,
    heroUrl: PACKSHOTS.last_heist,
    duration: "2h 12m",
    year: "2024",
    rating: "15+",
    cast: ["Robert Kane", "Lisa Park", "Omar Hassan"],
    personalizedScore: 80
  },
  {
    id: "d3",
    title: "Planet Earth III",
    description: "The latest in the acclaimed Attenborough series — a visually stunning and ecologically urgent look at the planet's most fragile ecosystems.",
    type: "documentary",
    genre: ["Nature", "Wildlife"],
    tags: ["nature", "wildlife", "relaxing", "calm", "earth", "documentary", "animals", "attenborough"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/hNwJPvA0SaFGKLW2oExiHFNDpNs.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3TOUvY2NZx8r31UHA3CQdRAY271.jpg",
    duration: "8 Episodes",
    year: "2023",
    rating: "U",
    personalizedScore: 90
  },
  {
    id: "se3",
    title: "Breaking Point",
    description: "A gripping psychological thriller following a detective who starts to question her own reality while investigating a series of connected disappearances.",
    type: "series",
    genre: ["Thriller", "Mystery"],
    tags: ["thriller", "mystery", "detective", "intense", "series", "psychological"],
    thumbnailUrl: PACKSHOTS.breaking_point,
    heroUrl: PACKSHOTS.breaking_point,
    duration: "1 Season",
    year: "2024",
    rating: "18+",
    cast: ["Clara Stone"],
    trending: true,
    personalizedScore: 87
  },
  {
    id: "s6",
    title: "Tour de France: Stage 20",
    description: "The penultimate mountain stage through the Alps. A gruelling test of endurance that will decide the yellow jersey.",
    type: "sport",
    genre: ["Cycling"],
    tags: ["cycling", "tour de france", "sports", "alps", "endurance", "race"],
    thumbnailUrl: PACKSHOTS.tour_france,
    heroUrl: PACKSHOTS.tour_france,
    duration: "4h 30m",
    year: "2024"
  },
  {
    id: "m5",
    title: "Ember",
    description: "After a devastating wildfire, a community must come together to rebuild — but old secrets threaten to tear them apart.",
    type: "movie",
    genre: ["Drama"],
    tags: ["drama", "community", "fire", "emotional", "rebuilding"],
    thumbnailUrl: PACKSHOTS.ember,
    heroUrl: PACKSHOTS.ember,
    duration: "1h 58m",
    year: "2023",
    rating: "12+",
    cast: ["Nina Brooks", "Sam Torres"]
  },
  {
    id: "s7",
    title: "Olympics: 100m Sprint Final",
    description: "The fastest humans on the planet compete for gold. Sub-10 second performances and raw athletic excellence.",
    type: "sport",
    genre: ["Athletics", "Olympics"],
    tags: ["olympics", "sprint", "athletics", "sports", "exciting", "fast", "gold"],
    thumbnailUrl: PACKSHOTS.olympics_sprint,
    heroUrl: PACKSHOTS.olympics_sprint,
    duration: "35m",
    year: "2024",
    personalizedScore: 91,
    moments: [
      { id: "m7a", title: "Photo finish — 9.79 seconds", timestamp: "00:10", thumbnailUrl: PACKSHOTS.moment_7 }
    ]
  },
  {
    id: "se4",
    title: "Kitchen Wars",
    description: "Celebrity chefs face off in intense culinary battles. High stakes, creative dishes, and dramatic eliminations.",
    type: "series",
    genre: ["Reality", "Food"],
    tags: ["cooking", "food", "comedy", "fun", "reality", "chef", "laugh"],
    thumbnailUrl: PACKSHOTS.kitchen_wars,
    heroUrl: PACKSHOTS.kitchen_wars,
    duration: "5 Seasons",
    year: "2019-2024",
    rating: "PG"
  },
  {
    id: "d4",
    title: "Blue Planet II",
    description: "Narrated by David Attenborough, this genre-defining series explores the mysteries of the world's oceans with stunning cinematography and ecological insight.",
    type: "documentary",
    genre: ["Nature", "Science"],
    tags: ["ocean", "nature", "relaxing", "calm", "science", "water", "deep", "documentary", "marine", "attenborough"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/j1NsoYYDYHnPkRr7Enqr8tlexgO.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/c7t4tidzOw8E88puHlGsqizViOw.jpg",
    duration: "7 Episodes",
    year: "2017",
    rating: "U",
    personalizedScore: 91
  },
  {
    id: "m6",
    title: "Velocity",
    description: "Two rival street racers must team up to take down a corrupt racing syndicate that controls the underground circuit.",
    type: "movie",
    genre: ["Action", "Racing"],
    tags: ["cars", "racing", "action", "exciting", "fast", "thriller", "speed"],
    thumbnailUrl: PACKSHOTS.velocity,
    heroUrl: PACKSHOTS.velocity,
    duration: "1h 52m",
    year: "2024",
    rating: "15+",
    cast: ["Jack Reeves", "Mei Lin"],
    personalizedScore: 76
  },
  {
    id: "s8",
    title: "Rugby World Cup Final",
    description: "The pinnacle of international rugby. Two nations battle for the Webb Ellis Cup in a ferocious contest.",
    type: "sport",
    genre: ["Rugby"],
    tags: ["rugby", "world cup", "sports", "intense", "exciting", "final"],
    thumbnailUrl: PACKSHOTS.rugby_wc,
    heroUrl: PACKSHOTS.rugby_wc,
    duration: "2h 10m",
    year: "2023"
  },
  {
    id: "se5",
    title: "Echoes",
    description: "Identical twins have secretly been swapping lives since they were teenagers. But when one goes missing, the truth starts to unravel.",
    type: "series",
    genre: ["Thriller", "Drama"],
    tags: ["twins", "mystery", "thriller", "drama", "series", "twist", "intense"],
    thumbnailUrl: PACKSHOTS.echoes,
    heroUrl: PACKSHOTS.echoes,
    duration: "1 Season",
    year: "2024",
    rating: "15+",
    cast: ["Emma Cross", "Emma Cross"],
    personalizedScore: 83
  },
  {
    id: "m7",
    title: "Frost",
    description: "An Arctic research team discovers something beneath the ice that was never meant to be found. Sci-fi horror at its chilling best.",
    type: "movie",
    genre: ["Sci-Fi", "Horror"],
    tags: ["arctic", "horror", "sci-fi", "thriller", "cold", "scary", "exciting"],
    thumbnailUrl: PACKSHOTS.frost,
    heroUrl: PACKSHOTS.frost,
    duration: "1h 42m",
    year: "2024",
    rating: "18+",
    cast: ["Dr. Alex Foster", "Yuki Ito"]
  },
  {
    id: "d5",
    title: "HyperNormalisation",
    description: "Adam Curtis' acclaimed essay film examines how governments, corporations, and media constructed a simplified version of reality to maintain control.",
    type: "documentary",
    genre: ["Politics", "Media"],
    tags: ["politics", "media", "society", "documentary", "educational", "history"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/tTqI2xoB7cGO7HASB22Sss6x44J.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/54HEQPoD7zWGGaCusDnDBG3aCFO.jpg",
    duration: "2h 46m",
    year: "2016",
    rating: "12+"
  },
  {
    id: "s9",
    title: "Australian Open: Women's Final",
    description: "An electrifying showdown under the Melbourne sun. Two titans of women's tennis battle for the first Grand Slam of the year.",
    type: "sport",
    genre: ["Tennis"],
    tags: ["tennis", "australian open", "sports", "match", "exciting", "women"],
    thumbnailUrl: PACKSHOTS.aus_open,
    heroUrl: PACKSHOTS.aus_open,
    duration: "2h 45m",
    year: "2024"
  },
  {
    id: "m8",
    title: "The Informant",
    description: "A journalist infiltrates a powerful cartel, but when her cover is blown, she must fight to survive and get the story out.",
    type: "movie",
    genre: ["Thriller", "Crime"],
    tags: ["journalist", "thriller", "crime", "intense", "undercover", "action"],
    thumbnailUrl: PACKSHOTS.informant,
    heroUrl: PACKSHOTS.informant,
    duration: "2h 01m",
    year: "2024",
    rating: "18+",
    cast: ["Sofia Vega"]
  },
  {
    id: "se6",
    title: "Laugh Track",
    description: "A behind-the-scenes comedy about the writers' room of a failing late-night talk show desperately trying to stay relevant.",
    type: "series",
    genre: ["Comedy"],
    tags: ["comedy", "funny", "laugh", "tv show", "behind the scenes", "fun"],
    thumbnailUrl: PACKSHOTS.laugh_track,
    heroUrl: PACKSHOTS.laugh_track,
    duration: "2 Seasons",
    year: "2023-2024",
    rating: "12+",
    cast: ["Tim Baker", "Priya Kapoor"]
  },
  {
    id: "s10",
    title: "UFC 305: Championship Fight",
    description: "The main event sees two undefeated fighters clash for the middleweight championship belt in an unforgettable night of combat sports.",
    type: "live",
    genre: ["MMA", "Combat Sports"],
    tags: ["ufc", "mma", "fighting", "sports", "live", "exciting", "intense", "combat"],
    thumbnailUrl: PACKSHOTS.ufc,
    heroUrl: PACKSHOTS.ufc,
    duration: "Live",
    year: "2024",
    personalizedScore: 86
  },
  {
    id: "d6",
    title: "All the Beauty and the Bloodshed",
    description: "Winner of the Golden Lion at Venice — a powerful portrait of artist Nan Goldin and her activism against the Sackler family and the opioid crisis.",
    type: "documentary",
    genre: ["Biography", "Activism"],
    tags: ["art", "activism", "society", "documentary", "biography", "inspiring"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/cvO51xxtIUHc5w5ZgFsigiFaUaO.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/anw7ONmtm1BrHd1Du0GQ5FoNd6r.jpg",
    duration: "1h 57m",
    year: "2022",
    rating: "15+"
  },
  {
    id: "m9",
    title: "Glass Tower",
    description: "A hostage situation in the world's tallest building. One security guard. Forty floors of danger. An explosive action spectacle.",
    type: "movie",
    genre: ["Action", "Thriller"],
    tags: ["action", "thriller", "exciting", "building", "hostage", "explosive", "intense"],
    thumbnailUrl: PACKSHOTS.glass_tower,
    heroUrl: PACKSHOTS.glass_tower,
    duration: "2h 08m",
    year: "2024",
    rating: "15+",
    cast: ["Marcus Webb", "Chen Yi"],
    personalizedScore: 79
  },
  {
    id: "se7",
    title: "Homestead",
    description: "Three families attempt to live completely off-grid in the Scottish Highlands. A heartwarming and sometimes hilarious reality series.",
    type: "series",
    genre: ["Reality", "Nature"],
    tags: ["reality", "nature", "relaxing", "scotland", "family", "calm", "off-grid"],
    thumbnailUrl: PACKSHOTS.homestead,
    heroUrl: PACKSHOTS.homestead,
    duration: "1 Season",
    year: "2024",
    rating: "U"
  },
  {
    id: "s11",
    title: "Cricket World Cup Final",
    description: "Two cricketing nations clash in a dramatic final at Lord's. The atmosphere is electric as history is made.",
    type: "sport",
    genre: ["Cricket"],
    tags: ["cricket", "world cup", "sports", "final", "exciting"],
    thumbnailUrl: PACKSHOTS.cricket_wc,
    heroUrl: PACKSHOTS.cricket_wc,
    duration: "8h",
    year: "2023"
  },
  {
    id: "m10",
    title: "Whisper",
    description: "A hearing-impaired woman discovers she can hear ghostly whispers from the walls of her new apartment. A slow-burn supernatural thriller.",
    type: "movie",
    genre: ["Horror", "Supernatural"],
    tags: ["horror", "supernatural", "thriller", "scary", "mystery"],
    thumbnailUrl: PACKSHOTS.whisper,
    heroUrl: PACKSHOTS.whisper,
    duration: "1h 36m",
    year: "2024",
    rating: "15+",
    cast: ["Rose Kim"]
  },
  {
    id: "d7",
    title: "The Power of Nightmares",
    description: "A provocative BBC series exploring the rise of radical Islamism and neoconservatism — and how the politics of fear reshaped the modern world.",
    type: "documentary",
    genre: ["Politics", "History"],
    tags: ["politics", "history", "society", "documentary", "educational", "bbc"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/tCzglFkgrkX5t7nLpvIgOJ3KCO7.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/A6gI6Z4Bsw2rWMqJP78SCahEZ8q.jpg",
    duration: "3 Episodes",
    year: "2004",
    rating: "12+"
  },
  {
    id: "se8",
    title: "Dark Frequency",
    description: "A podcast host investigating urban legends starts receiving calls from something that shouldn't exist. Horror anthology series.",
    type: "series",
    genre: ["Horror", "Anthology"],
    tags: ["horror", "podcast", "scary", "thriller", "supernatural", "series", "mystery"],
    thumbnailUrl: PACKSHOTS.dark_frequency,
    heroUrl: PACKSHOTS.dark_frequency,
    duration: "1 Season",
    year: "2024",
    rating: "18+"
  },
  {
    id: "s12",
    title: "Six Nations: England vs France",
    description: "Le Crunch — the fierce rugby rivalry crosses the Channel once more. A physical, tactical battle for Six Nations glory.",
    type: "sport",
    genre: ["Rugby"],
    tags: ["rugby", "six nations", "england", "france", "sports", "exciting"],
    thumbnailUrl: PACKSHOTS.six_nations,
    heroUrl: PACKSHOTS.six_nations,
    duration: "2h 05m",
    year: "2024"
  },
  {
    id: "m11",
    title: "Starbound",
    description: "A family of space colonists must survive when their generation ship suffers a catastrophic malfunction halfway to their new home.",
    type: "movie",
    genre: ["Sci-Fi", "Adventure"],
    tags: ["space", "sci-fi", "adventure", "family", "survival", "future", "stars"],
    thumbnailUrl: PACKSHOTS.starbound,
    heroUrl: PACKSHOTS.starbound,
    duration: "2h 22m",
    year: "2024",
    rating: "12+",
    cast: ["Dr. Lisa Okafor", "Ben Carter", "Maya Carter"],
    personalizedScore: 74
  },
  {
    id: "se9",
    title: "Stand Up: Raw",
    description: "The funniest comedians performing their most daring, uncensored sets in intimate venues across the globe.",
    type: "series",
    genre: ["Comedy", "Stand-Up"],
    tags: ["comedy", "funny", "laugh", "stand-up", "live", "fun"],
    thumbnailUrl: PACKSHOTS.standup_raw,
    heroUrl: PACKSHOTS.standup_raw,
    duration: "3 Seasons",
    year: "2022-2024",
    rating: "18+"
  },
  {
    id: "d8",
    title: "The Century of the Self",
    description: "Adam Curtis' landmark series explores how Freudian psychology shaped consumerism, politics, and identity in the 20th century.",
    type: "documentary",
    genre: ["History", "Psychology"],
    tags: ["psychology", "history", "society", "documentary", "educational", "bbc", "politics"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/baz9Mv5N8DryVZcr4wVxR02dytt.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/36DiL8XFUfnKOORpUWCHWy7ppyX.jpg",
    duration: "4 Episodes",
    year: "2002",
    rating: "12+"
  },
  {
    id: "s13",
    title: "La Liga: Barcelona vs Atletico Madrid",
    description: "A tactical masterclass between two Spanish giants. Every pass and tackle matters in this pivotal league fixture.",
    type: "sport",
    genre: ["Football", "Soccer"],
    tags: ["la liga", "barcelona", "atletico", "football", "soccer", "sports", "match"],
    thumbnailUrl: PACKSHOTS.la_liga,
    heroUrl: PACKSHOTS.la_liga,
    duration: "2h",
    year: "2024",
    moments: [
      { id: "m13a", title: "Free kick goal from 25 yards", timestamp: "34:20", thumbnailUrl: PACKSHOTS.moment_8 }
    ]
  },
  {
    id: "m12",
    title: "Last Light",
    description: "When the sun begins to die 500 years early, humanity has one chance to ignite it back to life. An epic sci-fi drama.",
    type: "movie",
    genre: ["Sci-Fi", "Drama"],
    tags: ["space", "sci-fi", "drama", "sun", "survival", "future", "epic"],
    thumbnailUrl: PACKSHOTS.last_light,
    heroUrl: PACKSHOTS.last_light,
    duration: "2h 35m",
    year: "2024",
    rating: "12+",
    cast: ["James Adler", "Nora Svensen", "Dr. Raj Patel"]
  },
  {
    id: "s14",
    title: "EFL Cup Final: Liverpool vs Chelsea",
    description: "A thrilling Wembley showdown between two Premier League heavyweights battling for the first domestic trophy of the season.",
    type: "sport",
    genre: ["Football", "Soccer"],
    tags: ["efl cup", "liverpool", "chelsea", "football", "soccer", "sports", "final", "wembley"],
    thumbnailUrl: PACKSHOTS.efl_cup,
    heroUrl: PACKSHOTS.efl_cup,
    duration: "2h 05m",
    year: "2024",
    personalizedScore: 89,
    moments: [
      { id: "m14a", title: "Opening goal header", timestamp: "22:10", thumbnailUrl: PACKSHOTS.moment_3 },
      { id: "m14b", title: "Penalty shootout drama", timestamp: "120:00", thumbnailUrl: PACKSHOTS.moment_1 }
    ]
  },
  {
    id: "s15",
    title: "Women's Euro 2025 Qualifiers",
    description: "England Lionesses take on their European rivals in a crucial qualifying match. Can they book their place at the tournament?",
    type: "live",
    genre: ["Football", "Soccer"],
    tags: ["women's football", "euros", "england", "lionesses", "football", "soccer", "sports", "live", "qualifying"],
    thumbnailUrl: PACKSHOTS.womens_euro,
    heroUrl: PACKSHOTS.womens_euro,
    duration: "Live",
    year: "2025",
    trending: true,
    personalizedScore: 93,
    moments: [
      { id: "m15a", title: "Beth Mead equaliser", timestamp: "67:30", thumbnailUrl: PACKSHOTS.moment_2 }
    ]
  },
  {
    id: "s16",
    title: "International Football Highlights",
    description: "Catch up on all the goals and drama from this week's international fixtures. Every goal, every card, every moment.",
    type: "sport",
    genre: ["Football", "Soccer"],
    tags: ["international", "football", "highlights", "soccer", "sports", "goals"],
    thumbnailUrl: PACKSHOTS.intl_football,
    heroUrl: PACKSHOTS.intl_football,
    duration: "45m",
    year: "2025"
  },
  {
    id: "s17",
    title: "Match Analysis: Tactical Breakdown",
    description: "Expert pundits break down the key tactical battles, formations, and pivotal moments from the biggest matches of the week.",
    type: "sport",
    genre: ["Football", "Soccer"],
    tags: ["analysis", "tactics", "football", "soccer", "sports", "pundit"],
    thumbnailUrl: PACKSHOTS.match_analysis,
    heroUrl: PACKSHOTS.match_analysis,
    duration: "30m",
    year: "2025"
  },
  {
    id: "s18",
    title: "Breaking Barriers: Women in Sport",
    description: "A powerful documentary series following female athletes breaking records and challenging conventions across multiple disciplines.",
    type: "documentary",
    genre: ["Sport", "Society"],
    tags: ["women", "sport", "documentary", "inspiring", "athletics", "football", "barriers"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/tUKomxy50suT4MyxjYfOJDkZUq3.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/1DYpBOVdb7Mzc9DgMCdIBTN1JEC.jpg",
    duration: "6 Episodes",
    year: "2024",
    rating: "PG",
    personalizedScore: 77
  },
  {
    id: "se10",
    title: "The Investigation",
    description: "A gripping true-crime drama based on real events. A detective pieces together evidence in a case that shocked the nation.",
    type: "series",
    genre: ["Crime", "Drama"],
    tags: ["crime", "drama", "investigation", "detective", "series", "true crime", "intense"],
    thumbnailUrl: PACKSHOTS.investigation,
    heroUrl: PACKSHOTS.investigation,
    duration: "4 Episodes",
    year: "2024",
    rating: "15+",
    cast: ["David Morrissey", "Keeley Hawes"],
    trending: true,
    personalizedScore: 88
  },
  {
    id: "se11",
    title: "Coastline Rescue",
    description: "Follow the brave RNLI crews and coastguard teams as they respond to emergencies along Britain's dramatic coastline.",
    type: "series",
    genre: ["Factual", "Reality"],
    tags: ["rescue", "coastguard", "reality", "drama", "sea", "factual", "heroes"],
    thumbnailUrl: PACKSHOTS.coastline,
    heroUrl: PACKSHOTS.coastline,
    duration: "2 Seasons",
    year: "2023-2024",
    rating: "PG"
  },
  {
    id: "d9",
    title: "Our Planet: Hidden Waters",
    description: "Dive beneath the surface of Earth's most remote waterways to discover ecosystems teeming with life and facing unprecedented threats.",
    type: "documentary",
    genre: ["Nature", "Wildlife"],
    tags: ["nature", "ocean", "water", "wildlife", "documentary", "relaxing", "environmental"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/j1NsoYYDYHnPkRr7Enqr8tlexgO.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/c7t4tidzOw8E88puHlGsqizViOw.jpg",
    duration: "50m",
    year: "2024",
    rating: "U",
    personalizedScore: 71
  },
  {
    id: "m13",
    title: "The Last Stand",
    description: "A retired special forces operative is drawn back into action when his family is targeted by an international crime syndicate.",
    type: "movie",
    genre: ["Action", "Thriller"],
    tags: ["action", "thriller", "military", "crime", "exciting", "intense", "explosive"],
    thumbnailUrl: PACKSHOTS.last_stand,
    heroUrl: PACKSHOTS.last_stand,
    duration: "2h 10m",
    year: "2024",
    rating: "15+",
    cast: ["Tom Hardy", "Florence Pugh"],
    personalizedScore: 84
  },
  {
    id: "se12",
    title: "The Royal Household",
    description: "An unprecedented look behind the gates of Britain's most famous residences. Explore the history, staff, and daily life of the monarchy.",
    type: "series",
    genre: ["Factual", "History"],
    tags: ["royal", "history", "documentary", "britain", "factual", "palace"],
    thumbnailUrl: PACKSHOTS.royal_household,
    heroUrl: PACKSHOTS.royal_household,
    duration: "3 Episodes",
    year: "2024",
    rating: "U"
  },
  {
    id: "d10",
    title: "Extreme Weather: A Year of Storms",
    description: "From hurricanes to heatwaves, follow meteorologists tracking the most devastating weather events of the year.",
    type: "documentary",
    genre: ["Science", "Nature"],
    tags: ["weather", "science", "nature", "documentary", "climate", "storms"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/hNwJPvA0SaFGKLW2oExiHFNDpNs.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3TOUvY2NZx8r31UHA3CQdRAY271.jpg",
    duration: "1h 30m",
    year: "2024",
    rating: "PG"
  },
  {
    id: "tr_im",
    title: "Inside the Manosphere",
    description: "Louis Theroux investigates the online world of men's rights activists, pick-up artists, and influencers promoting extreme views on masculinity.",
    type: "documentary",
    genre: ["Documentary", "Society"],
    tags: ["documentary", "society", "culture", "theroux", "bbc", "masculinity"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/ouOvRvsgF37yEx3D6ZLWyuxZFjE.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/cmpiLnDIdxQNFZLZZFRj1rSo7fW.jpg",
    duration: "1h 30m",
    year: "2024",
    rating: "15+",
    trending: true,
    personalizedScore: 78
  }
];

export const SEARCH_CATEGORIES = [
  "Sports", "Movies", "Series", "Live Events", "Documentaries", "Action", "Comedy", "Sci-Fi"
];

export const RECENT_SEARCHES = [
  "Champions League", "F1 highlights", "Action movies", "Sci-fi series", "Tennis finals"
];

export const TRENDING_SEARCHES = [
  "Premier League Live", "Spider-Man", "Basketball Finals", "New Documentaries", "Comedy Specials", "Olympics highlights"
];
