// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/axis-layouts/CinemaSpotlight.tsx": () => import("../components/mockups/axis-layouts/CinemaSpotlight.tsx"),
  "./components/mockups/axis-layouts/ContentForward.tsx": () => import("../components/mockups/axis-layouts/ContentForward.tsx"),
  "./components/mockups/axis-layouts/EditorialSplit.tsx": () => import("../components/mockups/axis-layouts/EditorialSplit.tsx")
};
