export interface ContentItem {
  id: string;
  title: string;
  description: string;
  type: 'movie' | 'series' | 'sport' | 'live' | 'documentary';
  genre: string[];
  thumbnailUrl: string;
  heroUrl: string;
  duration?: string;
  year?: string;
  rating?: string;
  personalizedScore?: number;
}

export const HERO_ITEMS: ContentItem[] = [
  {
    id: "hero_marty",
    title: "Marty Supreme",
    description: "Set in 1950s New York, a shoe salesman and table tennis hustler pursues his obsessive dream of becoming world champion.",
    type: "movie",
    genre: ["Drama", "Sport", "Biography"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/qKWDHofjMHPSEOTLaixkC9ZmjTT.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3iMoYSbI72Nwsvi7uSpqReLJVa6.jpg",
    duration: "2h 17m",
    year: "2025",
    rating: "15",
    personalizedScore: 99,
  },
  {
    id: "hero_spiderman",
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    type: "movie",
    genre: ["Animation", "Action"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/uc5U4GCZu9Z2Zb3yqk5fZfLwawR.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    duration: "2h 20m",
    year: "2023",
    rating: "PG",
    personalizedScore: 85,
  },
];

export const TRENDING: ContentItem[] = [
  {
    id: "t1",
    title: "Marty Supreme",
    description: "",
    type: "movie",
    genre: ["Drama"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/qKWDHofjMHPSEOTLaixkC9ZmjTT.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3iMoYSbI72Nwsvi7uSpqReLJVa6.jpg",
    year: "2025",
    rating: "15",
    personalizedScore: 99,
  },
  {
    id: "t2",
    title: "The White Lotus",
    description: "",
    type: "series",
    genre: ["Drama", "Comedy"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/7n06DhBEVVBDLxSwQK1RCUfeUbH.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/rCTLaPwuApDx8vLGjYZ9pRl7zRB.jpg",
    year: "2021-2025",
    rating: "18+",
    personalizedScore: 98,
  },
  {
    id: "t3",
    title: "Spider-Man: ATSV",
    description: "",
    type: "movie",
    genre: ["Animation", "Action"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/uc5U4GCZu9Z2Zb3yqk5fZfLwawR.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    year: "2023",
    rating: "PG",
    personalizedScore: 85,
  },
  {
    id: "t4",
    title: "Peaky Blinders",
    description: "",
    type: "series",
    genre: ["Crime", "Drama"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/8qPdsHxxJU493XbjeYAXStRo7z.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    year: "2013-2022",
    rating: "18+",
    personalizedScore: 92,
  },
  {
    id: "t5",
    title: "The Garfield Movie",
    description: "",
    type: "movie",
    genre: ["Animation", "Comedy"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/4kgVYUQBM0USgffyn1gzEv3a4t4.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/P82NAcEsLIYgQtrtn36tYsj41m.jpg",
    year: "2024",
    rating: "PG",
    personalizedScore: 78,
  },
  {
    id: "t6",
    title: "Free Solo",
    description: "",
    type: "documentary",
    genre: ["Adventure"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg",
    year: "2018",
    rating: "PG",
    personalizedScore: 88,
  },
];

export const TOP_PICKS: ContentItem[] = [
  {
    id: "p1",
    title: "Planet Earth II",
    description: "BAFTA-winning sequel showcasing Earth's wildlife in dazzling detail.",
    type: "documentary",
    genre: ["Nature"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/tUKomxy50suT4MyxjYfOJDkZUq3.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/1DYpBOVdb7Mzc9DgMCdIBTN1JEC.jpg",
    year: "2016",
    rating: "U",
    personalizedScore: 92,
  },
  {
    id: "p2",
    title: "Blue Planet II",
    description: "Genre-defining series explores the mysteries of the world's oceans.",
    type: "documentary",
    genre: ["Nature"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/j1NsoYYDYHnPkRr7Enqr8tlexgO.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/c7t4tidzOw8E88puHlGsqizViOw.jpg",
    year: "2017",
    rating: "U",
    personalizedScore: 91,
  },
  {
    id: "p3",
    title: "The White Lotus",
    description: "",
    type: "series",
    genre: ["Drama"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/7n06DhBEVVBDLxSwQK1RCUfeUbH.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/rCTLaPwuApDx8vLGjYZ9pRl7zRB.jpg",
    year: "2021-2025",
    rating: "18+",
    personalizedScore: 98,
  },
  {
    id: "p4",
    title: "Spider-Man: ATSV",
    description: "",
    type: "movie",
    genre: ["Animation"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/uc5U4GCZu9Z2Zb3yqk5fZfLwawR.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    year: "2023",
    rating: "PG",
    personalizedScore: 85,
  },
  {
    id: "p5",
    title: "Peaky Blinders",
    description: "",
    type: "series",
    genre: ["Crime"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/8qPdsHxxJU493XbjeYAXStRo7z.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    year: "2013-2022",
    rating: "18+",
    personalizedScore: 92,
  },
  {
    id: "p6",
    title: "Planet Earth III",
    description: "",
    type: "documentary",
    genre: ["Nature"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/hNwJPvA0SaFGKLW2oExiHFNDpNs.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3TOUvY2NZx8r31UHA3CQdRAY271.jpg",
    year: "2023",
    rating: "U",
    personalizedScore: 90,
  },
];

export const LIVE_SPORTS: ContentItem[] = [
  {
    id: "l1",
    title: "Premier League: Arsenal vs Liverpool",
    description: "",
    type: "live",
    genre: ["Football"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg",
    heroUrl: "https://image.tmdb.org/t/p/w500/sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg",
    duration: "LIVE",
    personalizedScore: 95,
  },
  {
    id: "l2",
    title: "NBA Finals: Game 7",
    description: "",
    type: "sport",
    genre: ["Basketball"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/bv47XMjZUhptKGFKIEoVA8pVsMT.jpg",
    heroUrl: "https://image.tmdb.org/t/p/w500/bv47XMjZUhptKGFKIEoVA8pVsMT.jpg",
    duration: "2h 30m",
    year: "2024",
    personalizedScore: 88,
  },
  {
    id: "l3",
    title: "Wimbledon Men's Final",
    description: "",
    type: "sport",
    genre: ["Tennis"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg",
    heroUrl: "https://image.tmdb.org/t/p/w500/5QApZVV8FUFlVxQpIK3Ew6cqotq.jpg",
    duration: "4h 10m",
    year: "2023",
    personalizedScore: 75,
  },
  {
    id: "l4",
    title: "Olympics: 100m Sprint Final",
    description: "",
    type: "sport",
    genre: ["Athletics"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/jxAbDJWvz4p1hoFpJYG5vY2dQmq.jpg",
    heroUrl: "https://image.tmdb.org/t/p/w500/jxAbDJWvz4p1hoFpJYG5vY2dQmq.jpg",
    duration: "35m",
    year: "2024",
    personalizedScore: 91,
  },
];

export const MOVIES: ContentItem[] = [
  {
    id: "mv1",
    title: "Marty Supreme",
    description: "",
    type: "movie",
    genre: ["Drama"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/qKWDHofjMHPSEOTLaixkC9ZmjTT.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3iMoYSbI72Nwsvi7uSpqReLJVa6.jpg",
    year: "2025",
    rating: "15",
  },
  {
    id: "mv2",
    title: "Spider-Man: ATSV",
    description: "",
    type: "movie",
    genre: ["Animation"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/uc5U4GCZu9Z2Zb3yqk5fZfLwawR.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    year: "2023",
    rating: "PG",
  },
  {
    id: "mv3",
    title: "The Garfield Movie",
    description: "",
    type: "movie",
    genre: ["Animation"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/4kgVYUQBM0USgffyn1gzEv3a4t4.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/P82NAcEsLIYgQtrtn36tYsj41m.jpg",
    year: "2024",
    rating: "PG",
  },
  {
    id: "mv4",
    title: "Free Solo",
    description: "",
    type: "documentary",
    genre: ["Adventure"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg",
    year: "2018",
    rating: "PG",
  },
  {
    id: "mv5",
    title: "Planet Earth III",
    description: "",
    type: "documentary",
    genre: ["Nature"],
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/hNwJPvA0SaFGKLW2oExiHFNDpNs.jpg",
    heroUrl: "https://image.tmdb.org/t/p/original/3TOUvY2NZx8r31UHA3CQdRAY271.jpg",
    year: "2023",
    rating: "U",
  },
];

export const NAV_ITEMS = ["Home", "Sports", "Movies", "Series", "Live"];

export const AXIS_LOGO = "https://images.deltatre.com/image/private/t_q_best/v1711553662/prd/assets/products/logos/axis-logo.png";
